project:
  type: website

website:
  title: Enrique Mosqueira Rubio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mrenrique
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: Cosmo
    css: styles.css



